{:theme "default",
 :title "CategoLJ",
 :port 8080,
 :charset "UTF-8",
 :static-dir ["/css/" "/images/" "/js/"],
 :category-separator "::"
 ;; MockDataAccess
 ;; :daccess {:ns am.ik.categolj.daccess.mock.daccess,
 ;;           :params {}},
 
 ;; MirageDataAccess
 :daccess {:ns am.ik.categolj.daccess.mirage.daccess,
           :params {:db {:classname "org.hsqldb.jdbcDriver"
                         :subprotocol "hsqldb"
                         :subname "mem:categolj"
                         :user "sa"
                         :password ""}
                    :ddl ["CREATE TABLE Entry
                          (id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY, 
                           title VARCHAR(256), 
                           content VARCHAR(256), 
                           created_at TIMESTAMP, 
                           updated_at TIMESTAMP)",                    
                          "CREATE TABLE Category
                          (id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
                           name VARCHAR(256),
                           index INT)",
                          "CREATE INDEX CTGRY_NAME_INDEX_IDX ON Category(name, index)",
                          "CREATE TABLE EntryCategory
                          (entry_id BIGINT CONSTRAINT ENTRY_FK REFERENCES Entry(id) ON DELETE CASCADE,
                           category_id BIGINT CONSTRAINT CATEGORY_FK REFERENCES Category(id) ON DELETE CASCADE)",
                          "CREATE INDEX CTGRY_ENTRY_ENTRY_IDX ON EntryCategory(entry_id)",
                          "CREATE INDEX CTGRY_ENTRY_CTGRY_IDX ON EntryCategory(category_id)"
                          ]}},
 :count-per-page 3,
 :count-of-recently 5}