{:theme "default",
 :title "CategoLJ",
 :port 8080,
 :charset "UTF-8",
 :static-dir ["/css/" "/images/" "/js/"],

 ;; MockDataAccess
 ;; :daccess {:ns am.ik.categolj.daccess.mock.daccess,
 ;;           :params {}},
 
 ;; MirageDataAccess
 :daccess {:ns am.ik.categolj.daccess.mirage.daccess,
           :params {:db {:classname "org.hsqldb.jdbcDriver"
                         :subprotocol "hsqldb"
                         :subname "mem:categolj"
                         :user "sa"
                         :password ""}
                    :ddl "CREATE TABLE ENTITY 
                          (ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY, 
                           TITLE VARCHAR(256), 
                           CONTENT VARCHAR(256), 
                           CREATED_AT TIMESTAMP, 
                           UPDATED_AT TIMESTAMP)"}},
 :count-per-page 5}